### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by ssanduli** [ssanduli/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by serhii-sanduliak** [comment]
https://www.facebook.com/DonaldTrump/
https://www.donaldjtrump.com/
realDonaldTrump@whitehouse.gov
https://twitter.com/realdonaldtrump
https://www.instagram.com/realdonaldtrump
