### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ssanduli** [ssanduli/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by serhii-sanduliak** [comment]
My family’s name was originally Drumpf or Drumpft but changed to Trump when the Thirty Years’ War occurred in the 1600s.
I attended the New York Military Academy aka NYMA to whom I credit much of my success to.
I attended Fordham University, Wharton School at the University of Pennsylvania and graduated Wharton in 1968 with a Bachelor of Science degree in economics.
I avoided being drafted into the military by getting four student deferments. After being determined twice to be fit for duty, I got a 1-Y medical deferment in October of 1968. Then in December 1969 I received a high placement number in the draft lottery that exempted me from service.
